services:
  feiertage:
    build:
      context: .
      args:
        VERSION: "${VERSION:-unknown}"
    container_name: feiertage-api
    ports:
      - "${FEIERTAGE_WEB_PORT:-8000}:8000"
    environment:
      - FEIERTAGE_WEB_PORT=${FEIERTAGE_WEB_PORT:-8000}
    restart: unless-stopped
